version: '3.8'

services:
  app:
    build: .
    container_name: php_app
    restart: always
    expose:
      - "9000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=notarios_db

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notarios
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "8003:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mysql_data:
